defaults:
  - default
  - _self_

# Override from `default` config
id: ${env.wrapper.robot}_${env.wrapper.env_name}
action_repeat: 1
max_episode_steps: 1000
sync_env: True
env_stats:
  Rewards/reach_avg_ep:
    - intrinsic
    - reach
    - mean
  Rewards/grasp_avg_ep:
    - intrinsic
    - grasp
    - mean
  Rewards/lift_avg_ep:
    - intrinsic
    - lift
    - mean
  Rewards/hover_avg_ep:
    - intrinsic
    - hover
    - mean
  Rewards/reach_max_ep:
    - intrinsic
    - reach
    - max
  Rewards/grasp_max_ep:
    - intrinsic
    - grasp
    - max
  Rewards/lift_max_ep:
    - intrinsic
    - lift
    - max
  Rewards/hover_max_ep:
    - intrinsic
    - hover
    - max

# Wrapper to be instantiated
wrapper:
  _target_: sheeprl.envs.robosuite.RobosuiteWrapper
  env_name: PickPlace
  env_config: single-arm-opposed
  robot: Panda
  bddl_file: null
  initial_joint_positions: null
  controller: OSC_POSE
  hard_reset: False
  horizon: ${env.max_episode_steps}
  reward_scale: 1.0
  reward_shaping:
    disable: False
    dense: False
    stages:
      reach:
        mult: 0.25
        disable: False
      grasp:
        mult: 0.1
        disable: False
        step: 0.0 # Step is the amount of immediate reward once this stage is reached i.e.: max(reach_reward) + step = min(grasp_reward) 
      lift:
        mult: 0.09817477042 # pi / 32
        disable: False
        step: 0.0
      hover:
        mult: 0.1
        disable: False
        step: 0.0
    tolerance: 0.01 # tolerance for considering a stage as "started" measured in absolute value
    # I tried setting it as a proportion but it doesn't work well with our mixing function for lifting (triggers early)
  ignore_done: True
  has_renderer: False
  has_offscreen_renderer: True
  use_camera_obs: True
  use_vector_obs: False
  control_freq: 20
  action_repeat: ${env.action_repeat}

# env_name:
# [0] 'Door'
# [1] 'Lift'
# [2] 'NutAssembly'
# [3] 'NutAssemblyRound'
# [4] 'NutAssemblySingle'
# [5] 'NutAssemblySquare'
# [6] 'PickPlace'
# [7] 'PickPlaceBread'
# [8] 'PickPlaceCan'
# [9] 'PickPlaceCereal'
# [10] 'PickPlaceMilk'
# [11] 'PickPlaceSingle'
# [12] 'Stack'
# [13] 'ToolHang'
# [14] 'TwoArmHandover'
# [15] 'TwoArmLift'
# [16] 'TwoArmPegInHole'
# [17] 'TwoArmTransport'
# [18] 'Wipe'

# env_config
# [0] 'single-arm-opposed'
# [1] 'single-arm-parallel'
# [2] 'bimanual'

# robot:
# [0] 'Baxter'
# [1] 'IIWA'
# [2] 'Jaco'
# [3] 'Kinova3'
# [4] 'Panda'
# [5] 'Sawyer'
# [6] 'UR5e'
